const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
const Student = require('./models/Student');
const Workshop = require('./models/Workshop');
const User = require('./models/User');

const path = require('path');
dotenv.config({ path: path.join(__dirname, '.env') });

const seedData = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB Connected for seeding');

        // 1. Ensure Users Exist
        const salt = await bcrypt.genSalt(10);
        const password = await bcrypt.hash('123', salt);

        let admin = await User.findOne({ email: 'admin@gmail.com' });
        if (!admin) {
            admin = await User.create({
                name: 'Admin User',
                email: 'admin@gmail.com',
                password,
                role: 'admin'
            });
            console.log('Admin user created');
        }

        let staff = await User.findOne({ email: 'staff@gmail.com' });
        if (!staff) {
            staff = await User.create({
                name: 'Staff Member',
                email: 'staff@gmail.com',
                password,
                role: 'staff'
            });
            console.log('Staff user created');
        }

        // 2. Seed Workshops
        const workshops = [
            { name: 'Financial Literacy', description: 'Basic money management.', points: 20 },
            { name: 'Social Wellness', description: 'Building better relationships.', points: 15 },
            { name: 'Emotional Support', description: 'Mental health and support.', points: 25 },
            { name: 'Career Development', description: 'Resume building and interview tips.', points: 30 },
            { name: 'Technical Skills', description: 'Learning core technologies.', points: 40 },
        ];

        for (const w of workshops) {
            let existing = await Workshop.findOne({ name: w.name });
            if (!existing) {
                await Workshop.create(w);
                console.log(`Workshop created: ${w.name}`);
            }
        }

        // 3. Seed Students (Assign to Staff)
        const students = [
            { name: 'John Doe', email: 'john@example.com', phone: '123-456-7890', points: 120, assignedStaff: staff._id },
            { name: 'Sara Smith', email: 'sara@example.com', phone: '234-567-8901', points: 250, assignedStaff: staff._id },
            { name: 'Mike Brown', email: 'mike@example.com', phone: '345-678-9012', points: 60, assignedStaff: staff._id },
            { name: 'Emily White', email: 'emily@example.com', phone: '456-789-0123', points: 180, assignedStaff: staff._id },
            { name: 'David Black', email: 'david@example.com', phone: '567-890-1234', points: 300, assignedStaff: staff._id },
            { name: 'Alice Green', email: 'alice@example.com', phone: '678-901-2345', points: 45, assignedStaff: admin._id },
        ];

        // Clear existing students to ensure fresh data with correct ObjectIds
        await Student.deleteMany();
        console.log('Cleared existing students');

        for (const s of students) {
            // studentId will be auto-generated by pre-save hook
            await Student.create(s);
            console.log(`Student created: ${s.name}`);
        }

        console.log('Sample data successfully seeded!');
        process.exit();
    } catch (error) {
        console.error(`Error: ${error.message}`);
        console.error(error.stack);
        process.exit(1);
    }
};

seedData();
